name: autofix.ci

on:
  pull_request:
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  autofix:
    runs-on: ${{ github.repository == 'antiwork/helper' && 'ubicloud-standard-4' || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - run: pnpm install --no-frozen-lockfile

      - name: Build Packages
        run: pnpm run-on-packages build
        shell: bash

      - name: Lint
        run: pnpm run lint --fix
        shell: bash

      - name: Format
        run: pnpm run format --write
        shell: bash

      - name: Typecheck
        shell: bash
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          cp .env.local.sample .env.local
          pnpm run typecheck

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
